### ISSUE TITLE
Android request problem

### ISSUE THREAD

**Issue by leblebi1** [bounswe/bounswe2018group8#46]
When I try to send requests to backend from android, my requests return "Unexpected response code 400".  Trying to solve this.

**Comment by umutoztunc** [comment]
It is the expected behaviour of the login endpoint. If login is successful, it returns a JWT token along with a User object with response code 200. If login is not successful, then it returns error details with response code 400.

Here is a code that I wrote to test it:
```
URL url = new URL(TARGET_URL);
HttpURLConnection conn = (HttpURLConnection) url.openConnection();
conn.setRequestMethod("POST");
conn.setRequestProperty("Content-Type", "application/json");
conn.setRequestProperty("Accept", "application/json");
conn.setDoOutput(true);

String username = "testuser";
String password = "passwd";
JSONObject obj = new JSONObject();
obj.put("username", username);
obj.put("password", password);

OutputStream os = conn.getOutputStream();
os.write(obj.toString().getBytes());
os.flush();
os.close();

InputStream _is;
if (conn.getResponseCode() < HttpURLConnection.HTTP_BAD_REQUEST) {
    _is = conn.getInputStream();
} else {
    _is = conn.getErrorStream();
}

String line;
BufferedReader reader = new BufferedReader(new InputStreamReader(_is));

while ((line = reader.readLine()) != null) {
    System.out.println(line);
}
reader.close();
```

I suggest you to do some abstractions like creating a SendPost method and/or creating some methods like Login, GetCurrentUser, Register, etc. Also, instead of sending x-www-form-urlencoded data, you should send it as JSON since there are some endpoints which require inputs that form encoding cannot handle such as /user/current/.

You can use [JSON Simple](http://www.java2s.com/Code/Jar/j/json-simple.htm) library or Google's [GSON](https://repo1.maven.org/maven2/com/google/code/gson/gson/) library for creating and dumping JSON objects.
