### ISSUE TITLE
Fixing bug about project creation.

### ISSUE THREAD

**Issue by KubraE** [bounswe/bounswe2018group8#59]
We are taking Error:403(forbidden) while trying to create project. Please turn frontend a documentation about how do you expect to receive the input. I suggest to use swagger or at least a shared google doc file, because WhatsApp is hard to maintain. Thank you.

**Comment by umutoztunc** [comment]
I have fixed the 403 Forbiden issue by removing the LoginRequiredMixin which uses Session Authentication whereas we use Token Authentication. I also removed UserPassesTestMixin and created a new permission called IsClient and used it instead.

The project creation bug also fixed by the removal of perform_create method in the CreateProject view. Instead I overrode the create function for the ProjectSerializer and removed the CreateProjectSerializer completely.

Now, you can create projects without getting any error.

**Comment by mehmetcalim** [comment]
I changed design of project creation according to changes at backend and it works now.
